mdp_template: deposition.mdp.epy
simulation_type: vacuum_deposition
forcefield_file: gromos54a7_atb.ff/forcefield.itp
escape_tolerance: 2.0 #nm
time_step: 0.0025 #ps
density_fraction_cutoff: 0.05
overhead_void_space: 12.0 # nm
use_gpu : False
description: "Vacuum deposition"
nstout: 100
insertion_xy_radius: 0.8 #nm
insertion_z_radius: 1.0 #nm
tau_t: 1.0 # ps
bath_width: 100
substrate:
  res_name: GRM
  pdb_file: resources/molecules/GRM_4nm.pdb
  itp_file: resources/molecules/GRM_4nm.itp
# To be filled:
# name, work_directory, mixture, other settings in input_config.yml
